### ISSUE TITLE
Textdraws

### ISSUE THREAD

**Issue by seiko02** [Codeblockz/Diverse-Roleplay-SA-MP-#10]
I'm talking about those big textdraws "Press H to enter ; SEATBELT ON ; ENGINE ON ; etc." They always get bugged on the screen and won't dissapear. Any fix?

**Comment by Codeblockz** [comment]
This happens when GetTickCount() surpasses the 32 bit integer limit. The computer you're hosting your SA:MP server on has been running for over 24 days straight. Restart it and it will work.
