### ISSUE TITLE
Bro...

### ISSUE THREAD

**Issue by CnRoma** [Codeblockz/Diverse-Roleplay-SA-MP-#12]
can open server  'file or fuction not found'
What`s problem...

**Comment by Codeblockz** [comment]
This is an issue that occurs when you're missing plugins, generally speaking.
Have a look at the 'nativechecker' plugin, it will help you find what plugin(s) you're missing.

Closing this issue as it's not related to the script.

**Comment by NagasakiX** [comment]
Hey mate i am getting this errors

   Error: Function not registered: 'SSCANF_Init'
   Error: Function not registered: 'SSCANF_IsConnected'
   Error: Function not registered: 'SSCANF_Join'
   Error: Function not registered: 'SSCANF_Leave'
   Error: Function not registered: 'mysql_format'
   Error: Function not registered: 'mysql_tquery'
   Error: Function not registered: 'mysql_escape_string'
   Error: Function not registered: 'GetDynamicObjectPos'
   Error: Function not registered: 'MoveDynamicObject'
   Error: Function not registered: 'sscanf'
   Error: Function not registered: 'cache_get_data'
   Error: Function not registered: 'cache_get_row'
   Error: Function not registered: 'CreateDynamicObject'
   Error: Function not registered: 'IsValidDynamicObject'
   Error: Function not registered: 'DestroyDynamicObject'
   Error: Function not registered: 'cache_insert_id'
   Error: Function not registered: 'Streamer_Update'
   Error: Function not registered: 'EditDynamicObject'
   Error: Function not registered: 'CreateDynamic3DTextLabel'
   Error: Function not registered: 'DestroyDynamic3DTextLabel'
   Error: Function not registered: 'cache_get_row_count'
   Error: Function not registered: 'cache_get_field_content_int'
   Error: Function not registered: 'cache_get_field_content_float'
   Error: Function not registered: 'cache_get_field_content'
   Error: Function not registered: 'TogglePlayerAllDynamicCPs'
   Error: Function not registered: 'DestroyDynamicCP'
   Error: Function not registered: 'CreateDynamicCP'
   Error: Function not registered: 'IsValidDynamicPickup'
   Error: Function not registered: 'DestroyDynamicPickup'
   Error: Function not registered: 'CreateDynamicPickup'
   Error: Function not registered: 'GetDynamicObjectRot'
   Error: Function not registered: 'SetDynamicObjectMaterialText'
   Error: Function not registered: 'Streamer_UpdateEx'
   Error: Function not registered: 'SetDynamicObjectRot'
   Error: Function not registered: 'SetDynamicObjectMaterial'
   Error: Function not registered: 'IsValidDynamic3DTextLabel'
   Error: Function not registered: 'IsValidDynamicMapIcon'
   Error: Function not registered: 'DestroyDynamicMapIcon'
   Error: Function not registered: 'CreateDynamicMapIcon'
   Error: Function not registered: 'AttachDynamicObjectToVehicle'
   Error: Function not registered: 'cache_get_row_int'
   Error: Function not registered: 'IsPlayerInDynamicCP'
   Error: Function not registered: 'TogglePlayerDynamicCP'
   Error: Function not registered: 'mysql_connect'
   Error: Function not registered: 'IsDynamicObjectMoving'
   Error: Function not registered: 'Streamer_GetTickRate'
   Error: Function not registered: 'Streamer_SetTickRate'
   Error: Function not registered: 'Streamer_GetMaxItems'
   Error: Function not registered: 'Streamer_SetMaxItems'
   Error: Function not registered: 'Streamer_GetVisibleItems'
   Error: Function not registered: 'Streamer_SetVisibleItems'
   Error: Function not registered: 'Streamer_GetRadiusMultiplier'
   Error: Function not registered: 'Streamer_SetRadiusMultiplier'
   Error: Function not registered: 'Streamer_IsToggleCameraUpdate'
   Error: Function not registered: 'Streamer_ToggleCameraUpdate'
   Error: Function not registered: 'Streamer_IsToggleIdleUpdate'
   Error: Function not registered: 'Streamer_ToggleIdleUpdate'
   Error: Function not registered: 'mysql_pquery'
   Error: Function not registered: 'Streamer_SetCellDistance'
   Error: Function not registered: 'Streamer_VisibleItems'
   Error: Function not registered: 'CountDynamicObjects'
   Error: Function not registered: 'CountDynamicPickups'
   Error: Function not registered: 'CountDynamicCPs'
   Error: Function not registered: 'CountDynamicMapIcons'
   Error: Function not registered: 'CountDynamic3DTextLabels'
   Error: Function not registered: 'CreateDynamicRectangle'
   Error: Function not registered: 'DestroyAllDynamicAreas'
   Error: Function not registered: 'DestroyAllDynamic3DTextLabels'
   Error: Function not registered: 'DestroyAllDynamicMapIcons'
   Error: Function not registered: 'DestroyAllDynamicCPs'
   Error: Function not registered: 'DestroyAllDynamicPickups'
   Error: Function not registered: 'DestroyAllDynamicObjects'
   Error: Function not registered: 'mysql_close'
   Error: Function not registered: 'GetPlayerVisibleDynamicCP'
