### ISSUE TITLE
Build.pwn

### ISSUE THREAD

**Issue by tryinghardyow** [Codeblockz/Diverse-Roleplay-SA-MP-#14]
Well, when i entered the server the Login dialog won't shown up, so i hope you can fix this, eh? hit me up, if you do.

**Comment by tryinghardyow** [comment]
I'm only using a Local IP, 127.0.0.1.

**Comment by Codeblockz** [comment]
Sorry, I don't actively monitor this repo... or this GitHub account at all.
This issue occurs when your connection to the MySQL server/database was unsuccessful! I hope you get it working.
