### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by tryinghardyow** [Codeblockz/Diverse-Roleplay-SA-MP-#16]
_**on XAMPP, it was working very well, but if i upload the mysql on phpmyadmin.co, it's
having a error, i'll give you a proof.
Here.**_

http://imgur.com/NYoJblU

**Comment by tryinghardyow** [comment]
bump

**Comment by Codeblockz** [comment]
Hey, sorry I don't really look at this repo. anymore (Or github account for that matter!) 
It seems like this is an issue with your permissions on your MySQL database itself. Likely your MySQL user account does not have CREATE access on that database.

I can assure you this is not an issue with the script or the SQL files that come with it. Hope you get it solved!
