### ISSUE TITLE
NPC

### ISSUE THREAD

**Issue by MaxAndolini** [Codeblockz/Diverse-Roleplay-SA-MP-#6]
Missing NPC Record 

Example

https://github.com/Codeblockz/Diverse-Roleplay-SA-MP-/blob/master/npcmodes/busroute.pwn

"route1"
"route2"
"route3"
"route4"
"route5"

etc.

Records Missing

https://github.com/Codeblockz/Diverse-Roleplay-SA-MP-/tree/master/npcmodes/recordings

**Comment by Codeblockz** [comment]
Oh, whoops! Thanks for noticing lol.

**Comment by Codeblockz** [comment]
Added, thanks.
