### ISSUE TITLE
Skills

### ISSUE THREAD

**Issue by MaxAndolini** [Codeblockz/Diverse-Roleplay-SA-MP-#8]
Missing Exp, Stats, Level systems etc.

And Will you give Fully SQL

**Comment by Codeblockz** [comment]
Not an issue, the gamemode isn't made to have a level, or stats system. If you want to add one feel free to fork the script. 

I don't think I'll post the full SQL because it's poorly done. The businesses and what not should be re-placed by you. Houses should be fine though.
