### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by MaxAndolini** [Codeblockz/Diverse-Roleplay-SA-MP-#9]
Missing .mp3 sounds.

**Comment by Codeblockz** [comment]
Yeah, don't even know if I still have them. I'll check later.

**Comment by MaxAndolini** [comment]
Bump.

**Comment by Codeblockz** [comment]
Can't find them.. I'll keep this issue opened til I one day decide to not be lazy and get replacement sounds or get my old laptop repaired.
